#!/bin/bash

THIS="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/$(basename ${BASH_SOURCE[0]})";
THISDIR="$(dirname "${THIS}")";
. "${THISDIR}/functions.sh";

for x in herdr jq yq; do
	which $x &>/dev/null || { echo "You must brew install $x first" && exit 1; }
done

export HERDR_BASE_DIR="${HOME}/.config/herdr";
export HERDER_PLUGIN_CONFIG_DIR="${HERDR_BASE_DIR}/plugins/config";
export HERDR_CONFIG="${HERDR_BASE_DIR}/config.toml";
HERDR_LOCAL_CONFIG="${HERDR_BASE_DIR}/config.local.toml";
CONFIG_D="${THISDIR}/herdr/config.d";

mkdir -p "${HERDER_PLUGIN_CONFIG_DIR}";

# Detect whether we're inside a devcontainer; *.devcontainer.toml fragments in
# config.d only apply there.
IS_DEVCONTAINER="false";
if [[ -n "${REMOTE_CONTAINERS}" || -n "${CODESPACES}" || -f /.devcontainer ]] || { [[ -f /.dockerenv ]] && [[ -d /workspaces ]]; }; then
	IS_DEVCONTAINER="true";
fi

echo "Updating herdr config...";

# Collect config.d fragments in sorted (filename) order, skipping
# *.devcontainer.toml fragments unless we're in a devcontainer.
CONFIG_FILES=();
for f in "${CONFIG_D}"/*.toml; do
	[[ -e "$f" ]] || continue;
	[[ "$f" == *.devcontainer.toml && "${IS_DEVCONTAINER}" != "true" ]] && continue;
	CONFIG_FILES+=("$f");
done

# Concatenate the fragments into a combined config...
COMBINED_JSON="$(cat "${CONFIG_FILES[@]}" | yq -p toml -o json '.' 2>/dev/null)";

# ...then let config.local.toml override anything set in it via a deep merge
# (local wins on conflicts). jq's `*` replaces arrays wholesale, which would
# drop every base keybinding as soon as config.local.toml defines a single
# [[keys.command]]. So keys.command is special-cased: base and local bindings
# are concatenated and de-duplicated by .key, keeping the latest (local) one.
if [[ -f "${HERDR_LOCAL_CONFIG}" ]]; then
	LOCAL_JSON="$(yq -p toml -o json '.' "${HERDR_LOCAL_CONFIG}" 2>/dev/null)";
	[[ -z "${LOCAL_JSON}" ]] && LOCAL_JSON="{}";
	FINAL_JSON="$(jq -n --argjson base "${COMBINED_JSON}" --argjson local "${LOCAL_JSON}" '
		($base * $local)
		| ( (($base.keys.command // []) + ($local.keys.command // []))
		    | reverse
		    | reduce .[] as $c ([]; if any(.[]; .key == $c.key) then . else . + [$c] end)
		    | reverse ) as $cmds
		| if ($cmds | length) > 0 then .keys.command = $cmds else . end
	' 2>/dev/null)";
else
	FINAL_JSON="${COMBINED_JSON}";
fi

# Render back to TOML and write it with a provenance header. Build to a temp
# file so a failure never truncates the live config.
FINAL_TOML="$(printf '%s\n' "${FINAL_JSON}" | yq -p json -o toml 2>/dev/null)";
if [[ -z "${FINAL_TOML}" ]]; then
	echo "WARNING: failed to generate herdr config; leaving ${HERDR_CONFIG} unchanged." >&2;
else
	{
		echo "# Generated by ${THIS}";
		echo "# on $(date).";
		echo "# DO NOT EDIT: regenerate with herdr.sh. Put local overrides in ${HERDR_LOCAL_CONFIG}.";
		echo "# Derived from:";
		for f in "${CONFIG_FILES[@]}"; do echo "#   - ${f}"; done;
		[[ -f "${HERDR_LOCAL_CONFIG}" ]] && echo "#   - ${HERDR_LOCAL_CONFIG} (local overrides)";
		echo "";
		printf '%s\n' "${FINAL_TOML}";
	} > "${HERDR_CONFIG}.tmp" && mv "${HERDR_CONFIG}.tmp" "${HERDR_CONFIG}";
fi

[[ "${REINSTALL_PLUGINS}" == "true" || ! -d "${HERDER_PLUGIN_CONFIG_DIR}/jamesboehmer.command-palette" ]] && herdr plugin install jamesboehmer/herdr-command-palette --yes;

herdr server reload-config 2>/dev/null;

[[ "${REINSTALL_PLUGINS}" == "true" || ! -f ${HOME}/.claude/skills/herdr/SKILL.md ]] && DISABLE_TELEMETRY=1 npx -y skills add ogulcancelik/herdr --skill herdr -g -a claude-code -y
[[ "${REINSTALL_PLUGINS}" == "true" || ! -f ${HOME}/.agents/skills/herdr/SKILL.md ]] && DISABLE_TELEMETRY=1 npx -y skills add ogulcancelik/herdr --skill herdr -g -a codex -y

[[ "${REINSTALL_PLUGINS}" == "true" ]] || echo "Set REINSTALL_PLUGINS=true to force update herdr plugins and skills";

