#!/bin/bash

#set -e
#set -x

inspection="$(mktemp)";
docker inspect docker-firefox > "${inspection}" 2>/dev/null;
if [[ $? -eq 0 ]]; then
	port="$(jq -r '.[0].NetworkSettings.Ports["5800/tcp"][0].HostPort' "${inspection}")";
	open http://localhost:${port};
else
	port=$(getfreeport)
	docker run -d --rm --name="docker-firefox" -p ${port}:5800 -v /docker/appdata/${USER}/firefox:/config:rw jlesage/firefox
	urlwaitspin http://localhost:${port} 200 true
fi
echo "Listening on http://localhost:${port}"
docker attach "docker-firefox"
