#!/bin/bash

[[ "$(uname -s)" != "Darwin" ]] && echo "Not OSX" && exit;

_setbluetoothaptx() {
	sudo defaults write bluetoothaudiod "Enable AptX codec" -bool true || exit 1;
	sudo defaults write bluetoothaudiod "Enable AAC codec" -bool true || exit 1;
	sudo defaults read bluetoothaudiod || exit 1;
}

_setbluetoothaptx
