#!/bin/bash

port=8889
docker run -d --rm --name swagger -it -p${port}:8080 swaggerapi/swagger-editor
urlwaitspin http://localhost:${port} 200 true
echo "Listening on http://localhost:${port}"
docker attach swagger