#!/bin/bash

[[ $# -ge 1 ]] || { echo "Usage: $0 <url> [<expectedStatus:200> [<openUrl:false>]" && exit 1; }

url="${1}";
expectedStatus="${2:-200}";
openUrl="${3:-false}";
timeout=300;
sp="⣾⣽⣻⢿⡿⣟⣯⣷";
i=0;
until [[ $(curl -o /dev/null -sw "%{http_code}" "${url}") == "${expectedStatus}" && ${timeout} -gt 0 ]]
do
    [[ "${BASH_VERSION}" != "" ]] && printf "\b${sp:i++%${#sp}:1}"
    if [[ "${ZSH_VERSION}" != "" ]]
    then
        ((i%=${#sp}));
        ((i+=1));
        printf "\b${${(@z)sp}[$i]//\"}"
    fi
    sleep .1
    ((timeout-=1))
    [[ ${timeout} -le 0 ]] && printf "\b \b" && exit 1;
done
printf "\b \b";
[[ "${openUrl}" == "true" ]] && open "${url}";
exit 0;
