#!/bin/bash

NAMESPACE="";

if [[ $# -lt 1 ]]
then
	echo "Usage: git ssh-config <namespace>";
	exit 1;
fi

NAMESPACE=".${1}";

echo "Pick a file to use for git-ssh identity:";

select PRIVKEY in $(find ~/.ssh ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys -name '*.pub' 2>/dev/null | while read line; do echo "$line:$(awk '{print $NF}' $line)" ; done)
do
	break
done

mkdir -p ~/.local;
git config --file ~/.local/${NAMESPACE}.gitconfig core.sshCommand "ssh -i $(echo "${PRIVKEY}" | awk -F: '{print $1}')"

echo "Updated ~/.local/${NAMESPACE}.gitconfig"