#!/bin/bash

NAMESPACE="";

if [[ $# -lt 1 ]]
then
	echo "Usage: git ssh-config <namespace>";
	exit 1;
fi

NAMESPACE=".${1}";

echo "Pick a file to use for git-ssh identity:";

select PRIVKEY in $(find ~/.ssh/ -name '*.pub' | while read line; do find $(dirname $line) -name $(basename ${line/.pub/}); done)
do
	break
done

mkdir -p ~/.local;
git config --file ~/.local/${NAMESPACE}.gitconfig core.sshCommand "ssh -i ${PRIVKEY}"

echo "Updated ~/.local/${NAMESPACE}.gitconfig"