#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo "Usage: git gpg-config <namespace> [openpgp|ssh|codespace]";
	exit 1;
fi

NAMESPACE=".${1}";

if [[ $# -gt 1 ]]
then
	METHOD="${2}"
fi

if [[ -z ${METHOD} ]]
then
	echo "Which method do you want to use for signing commits?"

	select METHOD in openpgp ssh codespace
	do
		break
	done
fi

case $METHOD in
	openpgp )
		echo "Pick a GPG key to use for openpgp git commit signatures:";

		select KEYID in $(gpg -K | grep -E -A2 '^sec.+expires:' | grep -v '^sec' | grep -v '\-\-' | xargs -L2 | tr -d '<>' | awk '{print $1 ":" $NF}' | tr '\n' ' ')
		do
			break
		done

		KEYID="$(echo "${KEYID}" | awk -F: '{print $1}')";

		mkdir -p ~/.local;
		git config --file ~/.local/${NAMESPACE}.gitconfig user.signingKey "${KEYID}";
		git config --file ~/.local/${NAMESPACE}.gitconfig commit.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig tag.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig gpg.format openpgp;

		echo "Updated ~/.local/${NAMESPACE}.gitconfig";
		;;
	ssh )
		find ~/.ssh ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys -name '*.pub' 2>/dev/null | grep . &>/dev/null;
		if [[ $? -ne 0 ]]
		then
			echo "No SSH keys found!"
			exit
		fi

		echo "Pick an SSH key to use for ssh git commit signatures:";

		select PUBKEY in $(find ~/.ssh ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys -name '*.pub' 2>/dev/null | while read line; do echo "$line:$(awk '{print $NF}' $line)" ; done)
		do
			break
		done

		PUBKEY="$(echo "${PUBKEY}" | awk -F: '{print $1}')";
		PUBKEY_CONTENTS=""$(cat "${PUBKEY}" | awk '{print $1 FS $2}')"";

		TMPFILE="$(mktemp)";
		echo "* ${PUBKEY_CONTENTS}" > ${TMPFILE};

		if [[ -f ~/.ssh/allowed_signers ]]
		then
			cat ~/.ssh/allowed_signers >> ${TMPFILE};
		fi

		cat "${TMPFILE}" | sort -u > ~/.ssh/allowed_signers

		mkdir -p ~/.local;
		git config --file ~/.local/${NAMESPACE}.gitconfig user.signingKey "${PUBKEY}"; # "${PUBKEY_CONTENTS}";
		git config --file ~/.local/${NAMESPACE}.gitconfig commit.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig tag.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig gpg.format ssh;
		git config --file ~/.local/${NAMESPACE}.gitconfig gpg.ssh.allowedSignersFile '~/.ssh/allowed_signers'

		echo "Updated ~/.local/${NAMESPACE}.gitconfig and updated ~/.ssh/allowed_signers";
		if [[ ${PUBKEY} =~ .*com.maxgoedjen.Secretive.SecretAgent.* ]]
		then
			echo "Looks like you're using Secretive for your key signing.  Be sure the agent is running and SSH_AUTH_SOCK=~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
		fi
		;;
	codespace )
		echo "Using your codespace environment for git commit signing";

		mkdir -p ~/.local;
		git config --file ~/.local/${NAMESPACE}.gitconfig commit.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig tag.gpgSign true;
		git config --file ~/.local/${NAMESPACE}.gitconfig gpg.format openpgp;

		echo "Updated ~/.local/${NAMESPACE}.gitconfig";
		;;
	* )
		echo "Unknown method: $METHOD"
		exit 1;
		;;

esac
